version: "3.6"
services:
  api:
    container_name: mainnet-api
    build:
      context: api
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 3001:3001
    env_file: mainnet.env
  indexer:
    container_name: mainnet-indexer
    build:
      context: indexer
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: mainnet.env
  redis:
    container_name: mainnet-redis
    image: redis:7.2-alpine
    command: redis-server --appendonly yes --appendfsync always
    restart: always
    volumes:
      - redis-data:/mnt/redis

volumes:
  redis-data:
