version: "3.6"
services:
  api:
    container_name: testnet-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: testnet.api.env
    ports:
      - "127.0.0.1:3008:3001"
  redis:
    container_name: testnet-redis
    image: redis:7.2-alpine
    command: redis-server --appendonly yes --appendfsync always
    restart: always
    volumes:
      - redis-data:/mnt/redis

volumes:
  redis-data:
