name: Deploy NearBlocks Gateway

on:
  push:
    branches:
      - main
    paths:
      - "apps/app/**"
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - "apps/app/**"

jobs:
  deploy-mainnet:
    runs-on: ubuntu-latest
    name: Deploy NearBlocks Gateway

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GATEWAY_SSH_HOSTS }}
          sync: true
          username: ${{ secrets.GATEWAY_SSH_USER }}
          key: ${{ secrets.GATEWAY_SSH_KEY }}
          script: sh deploy.sh